import express from "express";
import path from "path";
import dotenv from "dotenv";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type, FunctionDeclaration } from "@google/genai";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Initialize Gemini API client
const apiKey = process.env.GEMINI_API_KEY;
const ai = apiKey
  ? new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    })
  : null;

// Function declarations for tool use
const addTaskTool: FunctionDeclaration = {
  name: "addTask",
  description: "Add a new task to the user's to-do list.",
  parameters: {
    type: Type.OBJECT,
    properties: {
      title: {
        type: Type.STRING,
        description: "The title of the task. Keep it active and clear.",
      },
      dueTime: {
        type: Type.STRING,
        description: "Optional due time, e.g. '14:00', '18:30', or 'evening'.",
      },
      priority: {
        type: Type.STRING,
        description: "Optional priority level. Must be 'low', 'medium', or 'high'. Default is 'medium'.",
      },
      category: {
        type: Type.STRING,
        description: "Optional category/tag, e.g., 'Work', 'Personal', 'Health', 'Finance', 'Study'.",
      },
    },
    required: ["title"],
  },
};

const removeTaskTool: FunctionDeclaration = {
  name: "removeTask",
  description: "Delete or remove a task from the to-do list by its title.",
  parameters: {
    type: Type.OBJECT,
    properties: {
      title: {
        type: Type.STRING,
        description: "The title of the task to remove (can be case-insensitive or partial match).",
      },
    },
    required: ["title"],
  },
};

const completeTaskTool: FunctionDeclaration = {
  name: "completeTask",
  description: "Mark a task as completed.",
  parameters: {
    type: Type.OBJECT,
    properties: {
      title: {
        type: Type.STRING,
        description: "The title of the task to complete (can be case-insensitive or partial match).",
      },
    },
    required: ["title"],
  },
};

const addHabitTool: FunctionDeclaration = {
  name: "addHabit",
  description: "Add a new recurring habit to the habit tracker.",
  parameters: {
    type: Type.OBJECT,
    properties: {
      name: {
        type: Type.STRING,
        description: "The name of the habit, e.g., 'Drink 2L water', 'Read 10 pages', 'Exercise'.",
      },
      frequency: {
        type: Type.STRING,
        description: "How often the habit is tracked. Must be 'daily' or 'weekly'.",
      },
    },
    required: ["name", "frequency"],
  },
};

const logHabitCompletionTool: FunctionDeclaration = {
  name: "logHabitCompletion",
  description: "Check off/log completion of a habit for a specific date (or today).",
  parameters: {
    type: Type.OBJECT,
    properties: {
      name: {
        type: Type.STRING,
        description: "The name of the habit to complete (case-insensitive or partial match).",
      },
      date: {
        type: Type.STRING,
        description: "Optional date in 'YYYY-MM-DD' format. If not provided, defaults to today's date.",
      },
    },
    required: ["name"],
  },
};

const startPomodoroTool: FunctionDeclaration = {
  name: "startPomodoro",
  description: "Start a Pomodoro focus timer session on the user's interface.",
  parameters: {
    type: Type.OBJECT,
    properties: {
      durationMinutes: {
        type: Type.NUMBER,
        description: "The focus period duration in minutes. Default is 25.",
      },
      breakMinutes: {
        type: Type.NUMBER,
        description: "The break period duration in minutes. Default is 5.",
      },
    },
  },
};

const saveDailyPlanTool: FunctionDeclaration = {
  name: "saveDailyPlan",
  description: "Save a smart, structured, time-ordered daily plan/schedule generated by the assistant.",
  parameters: {
    type: Type.OBJECT,
    properties: {
      items: {
        type: Type.ARRAY,
        description: "The list of schedule items ordered chronologically.",
        items: {
          type: Type.OBJECT,
          properties: {
            time: {
              type: Type.STRING,
              description: "Time of the item, e.g., '08:00 AM', '12:00 PM', '04:30 PM'.",
            },
            type: {
              type: Type.STRING,
              description: "Type of the event: 'task', 'habit', 'focus', 'rest', or 'custom'.",
            },
            title: {
              type: Type.STRING,
              description: "The descriptive title of the scheduled block, e.g., 'Morning Run' or 'Work Focus: Code Review'.",
            },
          },
          required: ["time", "type", "title"],
        },
      },
    },
    required: ["items"],
  },
};

const functionDeclarations = [
  addTaskTool,
  removeTaskTool,
  completeTaskTool,
  addHabitTool,
  logHabitCompletionTool,
  startPomodoroTool,
  saveDailyPlanTool,
];

// Helper to execute tools on server's local copy of state
function executeTool(name: string, args: any, state: any): any {
  console.log(`Executing tool ${name} with args:`, args);
  try {
    if (name === "addTask") {
      const { title, dueTime, priority, category } = args;
      const newTask = {
        id: "task-" + Date.now() + "-" + Math.random().toString(36).substr(2, 4),
        title,
        dueTime: dueTime || "",
        priority: priority || "medium",
        category: category || "General",
        completed: false,
        createdAt: new Date().toISOString(),
      };
      state.tasks = [newTask, ...state.tasks];
      return { success: true, message: `Successfully added task: "${title}"` };
    }

    if (name === "removeTask") {
      const { title } = args;
      const originalCount = state.tasks.length;
      state.tasks = state.tasks.filter(
        (t: any) => !t.title.toLowerCase().includes(title.toLowerCase())
      );
      const removedCount = originalCount - state.tasks.length;
      return {
        success: removedCount > 0,
        message: removedCount > 0
          ? `Successfully removed task matching "${title}"`
          : `No task found matching "${title}"`,
      };
    }

    if (name === "completeTask") {
      const { title } = args;
      let completedCount = 0;
      state.tasks = state.tasks.map((t: any) => {
        if (!t.completed && t.title.toLowerCase().includes(title.toLowerCase())) {
          completedCount++;
          return {
            ...t,
            completed: true,
            completedAt: new Date().toISOString(),
          };
        }
        return t;
      });
      return {
        success: completedCount > 0,
        message: completedCount > 0
          ? `Successfully completed task matching "${title}"`
          : `No uncompleted task found matching "${title}"`,
      };
    }

    if (name === "addHabit") {
      const { name: habitName, frequency } = args;
      const newHabit = {
        id: "habit-" + Date.now() + "-" + Math.random().toString(36).substr(2, 4),
        name: habitName,
        frequency: frequency || "daily",
        streak: 0,
        completedDates: [],
        createdAt: new Date().toISOString(),
      };
      state.habits = [newHabit, ...state.habits];
      return { success: true, message: `Successfully added habit: "${habitName}"` };
    }

    if (name === "logHabitCompletion") {
      const { name: habitName, date } = args;
      const targetDate = date || new Date().toISOString().split("T")[0];
      let logged = false;

      state.habits = state.habits.map((h: any) => {
        if (h.name.toLowerCase().includes(habitName.toLowerCase())) {
          if (!h.completedDates.includes(targetDate)) {
            h.completedDates.push(targetDate);
            logged = true;

            // Recalculate streak (simple calendar consecutive logic)
            h.streak = calculateStreak(h.completedDates);
          }
        }
        return h;
      });

      return {
        success: logged,
        message: logged
          ? `Logged completion of habit matching "${habitName}" for ${targetDate}`
          : `Habit matching "${habitName}" was already completed for ${targetDate} or not found.`,
      };
    }

    if (name === "startPomodoro") {
      const { durationMinutes, breakMinutes } = args;
      state.pomodoro = {
        ...state.pomodoro,
        isActive: true,
        durationMinutes: durationMinutes || 25,
        breakMinutes: breakMinutes || 5,
        timestamp: Date.now(),
      };
      return {
        success: true,
        message: `Started a Pomodoro focus timer session of ${durationMinutes || 25} minutes.`,
      };
    }

    if (name === "saveDailyPlan") {
      const { items } = args;
      state.dailyPlan = items.map((item: any, idx: number) => ({
        id: "plan-item-" + idx + "-" + Date.now(),
        time: item.time,
        type: item.type,
        title: item.title,
        completed: false,
      }));
      return { success: true, message: `Successfully saved a new daily plan with ${items.length} items.` };
    }

    return { error: `Tool "${name}" not recognized.` };
  } catch (err: any) {
    return { error: err.message || "An error occurred during tool execution." };
  }
}

// Simple consecutive date streak calculator
function calculateStreak(dates: string[]): number {
  if (!dates || dates.length === 0) return 0;
  const uniqueDates = Array.from(new Set(dates)).sort();
  let streak = 0;
  let todayStr = new Date().toISOString().split("T")[0];

  // Let's parse all dates to time offsets
  const dateObjs = uniqueDates.map((d) => new Date(d));
  let currentIdx = dateObjs.length - 1;

  // Verify if last date logged is today or yesterday
  const lastDate = dateObjs[currentIdx];
  const lastDateStr = uniqueDates[currentIdx];

  const today = new Date(todayStr);
  const yesterday = new Date(today);
  yesterday.setDate(yesterday.getDate() - 1);
  const yesterdayStr = yesterday.toISOString().split("T")[0];

  if (lastDateStr !== todayStr && lastDateStr !== yesterdayStr) {
    // Streak broken if last log is earlier than yesterday
    return 0;
  }

  streak = 1;
  let lastChecked = lastDate;

  for (let i = currentIdx - 1; i >= 0; i--) {
    const prevDate = dateObjs[i];
    const diffTime = Math.abs(lastChecked.getTime() - prevDate.getTime());
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

    if (diffDays === 1) {
      streak++;
      lastChecked = prevDate;
    } else if (diffDays > 1) {
      break; // broken
    }
  }

  return streak;
}

// Core conversational API
app.post("/api/chat", async (req, res) => {
  if (!ai) {
    return res.status(500).json({
      error: "Gemini API key is not configured. Please add it to your secrets panel.",
    });
  }

  try {
    const { message, history, state, clientTime } = req.body;

    const currentTasks = state?.tasks || [];
    const currentHabits = state?.habits || [];
    const currentDailyPlan = state?.dailyPlan || [];
    const currentPomodoro = state?.pomodoro || {
      isActive: false,
      durationMinutes: 25,
      breakMinutes: 5,
      completedSessionsToday: 0,
    };

    const systemPrompt = `You are Nyra, an elegant, warm, and highly efficient AI Life Concierge.
Your goal is to help the user manage their tasks, habits, daily schedule, and focus sessions through intuitive, natural conversation.

Current Time/Date on User's Device: ${clientTime || new Date().toISOString()}

Below is the user's CURRENT productivity status on their device (stored entirely offline):
- To-Do List:
${currentTasks.length === 0 ? "No active tasks." : JSON.stringify(currentTasks.map((t: any) => ({ title: t.title, priority: t.priority, category: t.category, completed: t.completed, dueTime: t.dueTime })), null, 2)}

- Habits Tracker:
${currentHabits.length === 0 ? "No active habits." : JSON.stringify(currentHabits.map((h: any) => ({ name: h.name, frequency: h.frequency, streak: h.streak, completedDates: h.completedDates })), null, 2)}

- Daily Plan for Today:
${currentDailyPlan.length === 0 ? "No plan generated yet." : JSON.stringify(currentDailyPlan.map((p: any) => ({ time: p.time, type: p.type, title: p.title })), null, 2)}

- Pomodoro Timer State:
${JSON.stringify(currentPomodoro, null, 2)}

You can manage this system by calling tools. When the user asks you to do something (like add a task, check off a habit, start a pomodoro focus session, remove a task, or generate a daily plan), select the appropriate tool and call it.
When a tool is called, you will be given the result of the action, and then you must explain what you did in a warm, friendly, concise manner.
Always write your final replies using clean, elegant Markdown formatting. Avoid robotic jargon.
Feel free to suggest related tasks or positive habits (e.g., if they are starting a work Pomodoro, suggest drinking water or a quick stretch during their break).

If the user asks "Plan my day" or "What's my plan today?", use the \`saveDailyPlan\` tool to generate a smart chronological plan containing a combination of their active tasks, habits, and a couple of focus sessions or breaks, then explain the plan to them!
`;

    // Map client-side history to Gemini format
    const contents = history.map((h: any) => ({
      role: h.role,
      parts: [{ text: h.text }],
    }));

    // Append the latest user message
    contents.push({
      role: "user",
      parts: [{ text: message }],
    });

    // Make the initial request to Gemini with tools
    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: contents,
      config: {
        systemInstruction: systemPrompt,
        tools: [{ functionDeclarations }],
      },
    });

    const functionCalls = response.functionCalls;
    const localState = {
      tasks: [...currentTasks],
      habits: [...currentHabits],
      dailyPlan: [...currentDailyPlan],
      pomodoro: { ...currentPomodoro },
    };

    if (functionCalls && functionCalls.length > 0) {
      const toolParts = [];

      for (const call of functionCalls) {
        const { name, args } = call;
        const result = executeTool(name, args, localState);

        toolParts.push({
          functionResponse: {
            name: name,
            response: result,
          },
        });
      }

      // Preserve the exact first model response content (including text, functionCalls and thoughts with signatures)
      const modelContent = response.candidates?.[0]?.content;
      if (!modelContent) {
        throw new Error("No content received from initial model response.");
      }

      // Append tool execution context to contents and call Gemini a second time
      const followUpContents = [
        ...contents,
        modelContent,
        { role: "tool", parts: toolParts },
      ];

      const finalResponse = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: followUpContents,
        config: {
          systemInstruction: systemPrompt,
          tools: [{ functionDeclarations }],
        },
      });

      return res.json({
        text: finalResponse.text || "I have updated your schedule as requested.",
        updatedState: localState,
        actions: functionCalls.map((c) => ({ name: c.name, args: c.args })),
      });
    } else {
      // Direct conversational response
      return res.json({
        text: response.text || "How else can I help you today?",
        updatedState: localState,
        actions: [],
      });
    }
  } catch (error: any) {
    console.error("Error in /api/chat, applying local fallback:", error);

    try {
      const { message, state } = req.body;
      const lowerMsg = (message || "").toLowerCase().trim();

      const localState = {
        tasks: state?.tasks ? [...state.tasks] : [],
        habits: state?.habits ? [...state.habits] : [],
        dailyPlan: state?.dailyPlan ? [...state.dailyPlan] : [],
        pomodoro: state?.pomodoro ? { ...state.pomodoro } : {
          isActive: false,
          durationMinutes: 25,
          breakMinutes: 5,
          completedSessionsToday: 0,
        },
      };

      let replyText = "";
      let actionsExecuted: any[] = [];

      // 1. Plan Today
      if (lowerMsg.includes("plan") || lowerMsg.includes("schedule") || lowerMsg.includes("timeline") || lowerMsg.includes("routine")) {
        const items = [];
        let hour = 8;

        // Morning habit
        const morningHabits = localState.habits.filter((h: any) => h.frequency === "daily");
        if (morningHabits.length > 0) {
          items.push({
            time: `08:30 AM`,
            type: "habit",
            title: morningHabits[0].name,
          });
        } else {
          items.push({
            time: `08:30 AM`,
            type: "habit",
            title: "Morning sunlight walk",
          });
        }

        // Add pending tasks
        const pendingTasks = localState.tasks.filter((t: any) => !t.completed);
        if (pendingTasks.length > 0) {
          pendingTasks.slice(0, 3).forEach((task: any, idx: number) => {
            const timeStr = hour + idx === 12 ? "12:00 PM" : `${(hour + idx) % 12}:30 ${hour + idx >= 12 ? "PM" : "AM"}`;
            items.push({
              time: timeStr,
              type: "task",
              title: task.title,
            });
          });
        } else {
          items.push({
            time: "10:30 AM",
            type: "focus",
            title: "Deep work focus block",
          });
        }

        // Mid-day break
        items.push({
          time: "01:30 PM",
          type: "rest",
          title: "Mindfulness & recharge break",
        });

        executeTool("saveDailyPlan", { items }, localState);
        actionsExecuted.push({ name: "saveDailyPlan", args: { items } });

        replyText = `### 🌟 Local Heuristic Planner (API Fallback Mode)
I have successfully compiled a personalized schedule for your day using your active tasks and habits!

**Your Daily Rhythm Today:**
${items.map(item => `- **${item.time}** [${item.type.toUpperCase()}] ${item.title}`).join("\n")}

*Note: The Gemini cloud API is currently rate-limited (or daily quota is exhausted). I have seamlessly switched to Local Offline Processing to keep your workspace fully functional!*`;
      }
      // 2. Add Task
      else if (lowerMsg.startsWith("add task") || lowerMsg.startsWith("new task") || lowerMsg.startsWith("create task")) {
        let title = message.replace(/^(add task|new task|create task)/i, "").trim();
        title = title.replace(/^["']|["']$/g, "").trim();
        if (!title) title = "New productivity task";

        executeTool("addTask", { title, priority: "medium", category: "Routine" }, localState);
        actionsExecuted.push({ name: "addTask", args: { title, priority: "medium", category: "Routine" } });

        replyText = `### ✅ Task Added (API Fallback Mode)
I have added the task **"${title}"** to your list.

*Note: Seamlessly running in offline/local parsing mode due to API quota limits.*`;
      }
      // 3. Complete/Check Task
      else if (lowerMsg.startsWith("complete task") || lowerMsg.startsWith("check task") || lowerMsg.startsWith("finish task") || lowerMsg.includes("done task")) {
        let title = message.replace(/^(complete task|check task|finish task|done task|done)/i, "").trim();
        title = title.replace(/^["']|["']$/g, "").trim();
        if (!title) {
          const firstUncompleted = localState.tasks.find((t: any) => !t.completed);
          title = firstUncompleted ? firstUncompleted.title : "";
        }

        if (title) {
          const resTool = executeTool("completeTask", { title }, localState);
          actionsExecuted.push({ name: "completeTask", args: { title } });
          replyText = `### 👍 Task Completed (API Fallback Mode)
${resTool.message}

*Note: Seamlessly running in offline/local parsing mode due to API quota limits.*`;
        } else {
          replyText = `### ℹ️ Local Task Check (API Fallback Mode)
I couldn't find any pending tasks to check off. Add a new task first!`;
        }
      }
      // 4. Remove/Delete Task
      else if (lowerMsg.startsWith("remove task") || lowerMsg.startsWith("delete task")) {
        let title = message.replace(/^(remove task|delete task)/i, "").trim();
        title = title.replace(/^["']|["']$/g, "").trim();

        if (title) {
          const resTool = executeTool("removeTask", { title }, localState);
          actionsExecuted.push({ name: "removeTask", args: { title } });
          replyText = `### 🗑️ Task Removed (API Fallback Mode)
${resTool.message}

*Note: Seamlessly running in offline/local parsing mode due to API quota limits.*`;
        } else {
          replyText = `### ℹ️ Local Task Check (API Fallback Mode)
Please specify the name of the task you want to delete (e.g. "delete task [Name]").`;
        }
      }
      // 5. Add Habit
      else if (lowerMsg.startsWith("add habit") || lowerMsg.startsWith("new habit") || lowerMsg.startsWith("create habit")) {
        let name = message.replace(/^(add habit|new habit|create habit)/i, "").trim();
        name = name.replace(/^["']|["']$/g, "").trim();
        if (!name) name = "Daily hydration";

        executeTool("addHabit", { name, frequency: "daily" }, localState);
        actionsExecuted.push({ name: "addHabit", args: { name, frequency: "daily" } });

        replyText = `### 🔥 Habit Created (API Fallback Mode)
I have created the daily habit **"${name}"**. Check it off every day to build a streak!

*Note: Seamlessly running in offline/local parsing mode due to API quota limits.*`;
      }
      // 6. Log Habit Completion
      else if (lowerMsg.startsWith("log habit") || lowerMsg.startsWith("complete habit") || lowerMsg.startsWith("check habit") || lowerMsg.includes("log completion")) {
        let name = message.replace(/^(log habit|complete habit|check habit|log completion)/i, "").trim();
        name = name.replace(/^["']|["']$/g, "").trim();
        if (!name) {
          const firstHabit = localState.habits[0];
          name = firstHabit ? firstHabit.name : "";
        }

        if (name) {
          const resTool = executeTool("logHabitCompletion", { name }, localState);
          actionsExecuted.push({ name: "logHabitCompletion", args: { name } });
          replyText = `### ⭐ Habit Tracked (API Fallback Mode)
${resTool.message}

*Note: Seamlessly running in offline/local parsing mode due to API quota limits.*`;
        } else {
          replyText = `### ℹ️ Local Habit Check (API Fallback Mode)
I couldn't find any habits to track. Create a habit first!`;
        }
      }
      // 7. Start Pomodoro Focus Timer
      else if (lowerMsg.includes("pomodoro") || lowerMsg.includes("timer") || lowerMsg.includes("focus") || lowerMsg.includes("clock")) {
        const numbers = lowerMsg.match(/\d+/);
        const duration = numbers ? parseInt(numbers[0]) : 25;

        executeTool("startPomodoro", { durationMinutes: duration, breakMinutes: 5 }, localState);
        actionsExecuted.push({ name: "startPomodoro", args: { durationMinutes: duration, breakMinutes: 5 } });

        replyText = `### ⏱️ Focus Timer Initiated (API Fallback Mode)
I have activated a focus block for **${duration} minutes**. Turn off distractions and let's get down to business!

*Note: Seamlessly running in offline/local parsing mode due to API quota limits.*`;
      }
      // 8. General conversation placeholder
      else {
        replyText = `### 👋 Hello! (Local Concierge Fallback)
The cloud-based Gemini API has reached its daily quota limit for your project, but **I am still fully operational in Offline Fallback Mode!**

I can execute your productivity commands locally. Try typing:
- **"Plan my day"** or **"Plan today"** (saves a smart timeline of your habits/tasks)
- **"Add task [Name]"** (creates a new task)
- **"Complete task [Name]"** (checks off a task)
- **"Add habit [Name]"** (creates a new habit)
- **"Log habit [Name]"** (logs daily habit completion)
- **"Start focus [Minutes]"** (initiates a Pomodoro session)

How can I help you organize your flow right now?`;
      }

      return res.json({
        text: replyText,
        updatedState: localState,
        actions: actionsExecuted,
      });

    } catch (fallbackErr: any) {
      console.error("Local fallback error:", fallbackErr);
      res.status(500).json({
        error: error.message || "An unexpected error occurred while communicating with Gemini.",
      });
    }
  }
});

// Serve assets and fallbacks
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
